#!/bin/sh

BASE_DIR="."
[ -z $1 ] || BASE_DIR=$1

PORTAGE_DIR="/var/lib/portage/gentoo"
PORTAGE_TMP="/var/tmp/portage"
DISTFILES_DIR="/var/lib/portage/distfiles"
SRC_DIR="/usr/src"

[ -d $BASE_DIR/proc ] || { echo "probably no rootfs!!!" ; exit 1; }

umount $BASE_DIR/proc
umount $BASE_DIR/dev
umount $BASE_DIR/sys
umount $BASE_DIR/$PORTAGE_DIR
umount $BASE_DIR/$DISTFILES_DIR
umount $BASE_DIR/$PORTAGE_TMP
