#!/bin/sh

BASE_DIR="."
[ -z $1 ] || BASE_DIR=$1

PORTAGE_DIR="$BASE_DIR/var/lib/portage/gentoo"
PORTAGE_FILE="$PORTAGE_DIR.xz.sqfs"
DISTFILES_DIR="/var/lib/portage/distfiles"
PORTAGE_TMP="/var/tmp/portage"
SRC_DIR="/usr/src"

[ -d $BASE_DIR/proc ] || { echo "probably no rootfs!!!" ; exit 1; }

mount -t proc /proc $BASE_DIR/proc
mount --bind /dev $BASE_DIR/dev
mount --bind /dev/pts $BASE_DIR/dev/pts
mount --bind /dev/shm $BASE_DIR/dev/shm
mount --bind /sys $BASE_DIR/sys

mount --bind $DISTFILES_DIR $BASE_DIR/$DISTFILES_DIR
mount --bind $PORTAGE_TMP $BASE_DIR/$PORTAGE_TMP
mount --bind $SRC_DIR $BASE_DIR/$SRC_DIR

if [[ -e $PORTAGE_FILE ]]
then
	mount -t squashfs $PORTAGE_FILE $PORTAGE_DIR
fi

echo "run:"
echo "chroot $BASE_DIR /bin/zsh --login"
