#!/bin/sh

BASE_DIR="."
[ -z $1 ] || BASE_DIR=$1

PORTAGE_DIR="$BASE_DIR/var/lib/portage/gentoo"
PORTAGE_FILE="$PORTAGE_DIR.xz.sqfs"
DISTFILES_DIR="/var/lib/portage/distfiles"
PORTAGE_TMP="/var/tmp/portage"
SRC_DIR="/usr/src"

SYSTEMD_NSPAWN="/usr/bin/systemd-nspawn"

[ -d $BASE_DIR/proc ] || { echo "probably no rootfs!!!" ; exit 1; }

BINDS=""
for BIND in $SRC_DIR $PORTAGE_TMP $DISTFILES_DIR
do
	[ -d $BASE_DIR/$BIND ] && BINDS="$BINDS $BIND"
done

if [[ -e $PORTAGE_FILE ]]
then
	mount -t squashfs $PORTAGE_FILE $PORTAGE_DIR
fi

if [ -x $SYSTEMD_NSPAWN ]
then
	BINDS=`echo $BINDS | sed s/\ /\ --bind\ /g`

	$SYSTEMD_NSPAWN -D $BASE_DIR --bind $BINDS /bin/zsh

	if [[ -e $PORTAGE_FILE ]]
	then
		umount $PORTAGE_DIR
	fi
else
	mount -t proc /proc $BASE_DIR/proc

	for BIND in $BINDS /dev /dev/pts /dev/shm /sys
	do
		mount --bind $BIND $BASE_DIR/$BIND
	done

	echo "run:"
	echo "chroot $BASE_DIR /bin/zsh --login"
fi
